jdk:
  - oraclejdk8
os:
  - linux
language: scala

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # default stage is test
    - env: TEST="scalafmt+scalafix+docs"
      script:
        - ./bin/scalafmt --test
        - sbt scalafixCheck docs/docusaurusCreateSite
    - env: TEST="sbt test"
      script:
        - sbt sbt-metals/publishLocal test
    - env: TEST="sbt test"
      os: windows
      language:
        - node_js # Scala is not supported
      pre_install:
        - choco config set choco-cache
        - choco install jdk8
        - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
        - java -version
        - choco install sbt
      script:
        - sbt sbt-metals/publishLocal test
    - stage: release
      script: sbt ci-release docs/docusaurusPublishGhpages

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.coursier
    - choco-cache
  yarn: true

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

