language: scala
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # default stage is test
    - env: TEST="scalafmt+scalafix"
      script:
        - ./bin/scalafmt --test
        - sbt scalafixCheck
    - env: TEST="sbt test"
      script:
        - sbt startServer metalsSetup test
    - env: TEST="sbt-metals"
      script:
        - ./bin/run-scripted.sh
    - stage: release
      script: sbt ci-release docs/docusaurusPublishGhpages

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.coursier
  yarn: true

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

