name: "Check Scala nightly release"
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *
jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          apps: ""
      - name: "Query maven-central"
        run: |
          echo "3.2.0-RC1-bin-20220307-6dc591a-NIGHTLY" > broken
          echo "3.2.0-RC1-bin-20220308-29073f1-NIGHTLY" >> broken

          cs complete org.scala-lang:scala3-compiler_3: | grep NIGHTLY | grep -v -f partial.list | sort > all_nightly
          LAST_NIGHTLY_MTAG=$(cs complete org.scalameta:mtags_3 | grep NIGHTLY | grep -v -f broken | sort | tail -n 1 | cut -d "_" -f2)
          LAST_NIGHTLY_POS=$(grep -n $LAST_NIGHTLY_MTAG  all_nightly | cut -d ":" -f1)
          LAST_NIGHTLY_POS=$(($LAST_NIGHTLY_POS+1))
          NEW_NIGHTLIES=$(tail -n +$LAST_NIGHTLY_POS all_nightly)
          if [ ! -z "$NEW_NIGHTLIES" ]; then
            while IFS= read -r version; do
              gh workflow run mtags-auto-release.yml -f scala_version=$version
            done <<< "$NEW_NIGHTLIES"
          else
            echo "No new releases found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
